
default['magento']['license_agreement_accepted'] = 'no'
default['magento']['timezone'] = 'Europe/Madrid'
default['magento']['locale'] = 'es_ES'
default['magento']['default_currency'] = 'EUR'

default['magento']['web_path'] = '/vagrant'
default['magento']['db_host'] = 'localhost'
default['magento']['db_name'] = 'magento'
default['magento']['db_user'] = 'magento'
default['magento']['db_password'] = 'magento'
default['magento']['admin_user']['firstname'] = 'admin'
default['magento']['admin_user']['lastname'] = 'admin'
default['magento']['admin_user']['username'] = 'admin'
default['magento']['admin_user']['email'] = 'admin@example.com'
default['magento']['admin_user']['password'] = 'p4ssw0rd'
